### ISSUE TITLE
Uncaught exception error

### ISSUE THREAD

**Issue by tswolf** [hojanssen/contao_hoja_newsletter_extended#3]
Hi there!

I just installed your newest alpha as shown in Contao Extension Repo. Installation worked like a charm, so does the use of elements in a newsletter I am creating. But on the very instant I try to test-send the newsletter, it throws an error (I erased my user credentials and put in ### instead):

**PHP Fatal error: Uncaught exception 'Error' with message 'Call to a member function loadDetails() on null' thrown in ### system/modules/hoja_newsletter_extended/classes/NewsletterExtended.php on line 833
#0 ### system/modules/hoja_newsletter_extended/classes/NewsletterExtended.php(349): HoJa\NLExtended\NewsletterExtended::getUnsubscriptionLink('1')
#1 ### system/modules/core/classes/Backend.php(430): HoJa\NLExtended\NewsletterExtended->send(Object(Contao\DC_Table))
#2 ### system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('newsletter')
#3 ### contao/main.php(20): Contao\BackendMain->run()
#4 {main}**

Any idea what that might be?

Kudos to the creator and thx in advance!
Tom

**Comment by hojak** [comment]
Hi,
which version of Contao was used?

Ciao,
Holger

**Comment by hojak** [comment]
Ah, I see. The problem is, that no unsubscription page was selected in the settings of the corresponding newsletter channel.

I'll add a fix to check for this setting today, but I recommend to use this setting, so that the unsubscription facilities can be used.

/Holger

**Comment by tswolf** [comment]
You're absolutely correct, I didn't put in a selection for unsubscribing there. After all, it's marked as an "optional" entry. I guess, it's not that optional at all then?

Contao version currently is v3.5.27. Didn't try running your extension on v4.4.0 yet.

**Comment by hojak** [comment]
Yeah, you're right, this parameter is intended as optional.
I just added the corresponding patch here and in the contao extention repository.

/H

**Comment by andreasbrauchle** [comment]
Hi
I just installed your newsletter tool. All went very well. But I can't create a text for the newsletter:

[21-Feb-2018 12:26:16 Europe/Zurich] PHP Fatal error: Uncaught exception 'Exception' with message 'The table name must not be empty' thrown in /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/library/Contao/DcaLoader.php on line 48
#0 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/library/Contao/Controller.php(1318): Contao\DcaLoader->__construct('')
#1 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/library/Contao/Controller.php(1402): Contao\Controller::loadDataContainer('')
#2 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/classes/Versions.php(238): Contao\Controller->getParentEntries('', '1')
#3 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/classes/Versions.php(121): Contao\Versions->create()
#4 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/drivers/DC_Table.php(1818): Contao\Versions->initialize()
#5 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#6 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('newsletter')
#7 /home_p2/4/p/4projects.ch/htdocs/admin.4projects.ch/contao/main.php(20): Contao\BackendMain->run()
#8 {main}

I'm using Contao 3.5.31.

I really hope, you can help me.

Sincerely Yours, Andreas
